openapi: 3.0.0
info:
  title: BSCScan API
  description: Description in [BSCScan API](https://github.com/quanttb/bscscan-api).
  version: 0.0.1
  contact:
    email: tranthienbaoquan@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.htm
tags:
  - name: Block
    description: Everything about Block
    externalDocs:
      description: Find out more
      url: https://bscscan.com/
  - name: Transaction
    description: Everything about Transaction
    externalDocs:
      description: Find out more
      url: https://bscscan.com/
paths:
  /block/{blockId}:
    get:
      tags:
        - Block
      summary: Returns block by block number.
      parameters:
        - name: blockId
          in: path
          required: true
          description: Block number of query block
          schema:
            type: number
      responses:
        '200':
          description: Queried block
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BlockResponseModel'
        '500':
          description: Unexpected error.
  /transaction/{transactionHash}:
    get:
      tags:
        - Transaction
      summary: Returns transaction by transaction hash.
      parameters:
        - name: transactionHash
          in: path
          required: true
          description: Transaction hash of query transaction
          schema:
            type: string
      responses:
        '200':
          description: Queried transaction
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/TransactionResponseModel'
        '500':
          description: Unexpected error.
components:
  schemas:
    BlockResponseModel:
      properties:
        difficulty:
          type: string
        extraData:
          type: string
        gasLimit:
          type: number
        gasUsed:
          type: number
        hash:
          type: string
        logsBloom:
          type: string
        miner:
          type: string
        mixHash:
          type: string
        nonce:
          type: string
        number:
          type: number
        parentHash:
          type: string
        receiptsRoot:
          type: string
        sha3Uncles:
          type: string
        size:
          type: number
        stateRoot:
          type: string
        timestamp:
          type: number
        totalDifficulty:
          type: string
        transactionCount:
          type: number
        # transactions:
        #   type: string
        transactionsRoot:
          type: string
        # uncles:
        #   type: string
      required:
        - difficulty
        - extraData
        - gasUsed
        - gasLimit
        - hash
        - logsBloom
        - miner
        - mixHash
        - nonce
        - number
        - parentHash
        - receiptsRoot
        - sha3Uncles
        - size
        - stateRoot
        - timestamp
        - totalDifficulty
        - transactionCount
        # - transactions
        - transactionsRoot
        # - uncles
    TransactionResponseModel:
      properties:
        blockHash:
          type: number
        from:
          type: string
        gas:
          type: number
        gasPrice:
          type: string
        hash:
          type: string
        input:
          type: string
        nonce:
          type: number
        r:
          type: string
        s:
          type: string
        to:
          type: string
        transactionIndex:
          type: number
        v:
          type: string
        value:
          type: string
      required:
        - blockHash
        - from
        - gas
        - gasPrice
        - hash
        - input
        - nonce
        - r
        - s
        - to
        - transactionIndex
        - v
        - value
