/**
 * BSCScan API
 * Description in [BSCScan API](https://github.com/quanttb/bscscan-api).
 *
 * OpenAPI spec version: 0.0.1
 * Contact: tranthienbaoquan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BlockResponseModel { 
    difficulty: string;
    extraData: string;
    gasLimit: number;
    gasUsed: number;
    hash: string;
    logsBloom: string;
    miner: string;
    mixHash: string;
    nonce: string;
    number: number;
    parentHash: string;
    receiptsRoot: string;
    sha3Uncles: string;
    size: number;
    stateRoot: string;
    timestamp: number;
    totalDifficulty: string;
    transactionCount: number;
    transactionsRoot: string;
}